# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Josh Kennedy
description: "UI Designer & Front-end Developer"
url: http://joshkennedy.me
author:
  name: Josh Kennedy
  email: hello@joshkennedy.me
copyright: 2014
rss_path: /writing

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: /:categories/:title
paginate: 1
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true